CREATE TABLE users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACTIVE BOOLEAN NOT NULL, 
    AGE INTEGER NOT NULL, 
    NAME VARCHAR NOT NULL, 
    GENDER VARCHAR NOT NULL, 
    EMAIL VARCHAR NOT NULL
)