CREATE TABLE users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACTIVE BOOLEAN NOT NULL, 
    AGE INTEGER NOT NULL, 
    NAME VARCHAR NOT NULL, 
    GENDER VARCHAR NOT NULL, 
    EMAIL VARCHAR NOT NULL
);

CREATE TABLE events (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    START DATETIME NOT NULL,
    END DATETIME NOT NULL,
    ONLINE_EVENT BOOLEAN,
    LOCATION_ADDRESS VARCHAR NOT NULL,
    ORGANIZER_EMAIL VARCHAR NOT NULL,
    STATUS VARCHAR,
    CAPACITY INTEGER NOT NULL,
    ID_REISTRATION BIGINT NOT NULL,
    FOREIGN key (ID_REGISTRATION) REFERENCES REGISTRATIONS(ID)
);

CREATE TABLE registrations (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL VARCHAR NOT NULL,
    REGISTRATION_STATUS VARCHAR NOT NULL,
    EVENT_ID INTEGER,
    USER_ID INTEGER,
  	FOREIGN key (EVENT_ID) references EVENTS(EVENT_ID)
    FOREIGN key (USER_ID) references EVENTS(USER_ID)
);

